### ISSUE TITLE
ImportError: cannot import name 'WordTokenizer'

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/allennlp_imdb#2]
```
2020-11-20 13:25:39.774576: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/__init__.py", line 117, in main
    import_module_and_submodules(package_name)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/util.py", line 354, in import_module_and_submodules
    import_module_and_submodules(subpackage)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/util.py", line 354, in import_module_and_submodules
    import_module_and_submodules(subpackage)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/common/util.py", line 343, in import_module_and_submodules
    module = importlib.import_module(package_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/allennlp_imdb/allennlp_imdb/data/dataset_readers/__init__.py", line 1, in <module>
    from allennlp_imdb.data.dataset_readers.imdb import ImdbDatasetReader
  File "/content/allennlp_imdb/allennlp_imdb/data/dataset_readers/imdb.py", line 16, in <module>
    from allennlp.data.tokenizers import Tokenizer, WordTokenizer
ImportError: cannot import name 'WordTokenizer'
```

**Comment by ys7yoo** [comment]
https://github.com/allenai/vampire/issues/48
should downgrade allennlp?

**Comment by ys7yoo** [comment]
https://github.com/allenai/allennlp/issues/4228
https://github.com/allenai/allennlp/pull/3361

fix code?
