### ISSUE TITLE
Error loading TensorBoard visualizer

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/allennlp_imdb#3]
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-dd66094b0022> in <module>()
----> 1 get_ipython().magic('load_ext tensorboard.notebook')
      2 get_ipython().magic('tensorboard --logdir allennlp_imdb/storage/log')

6 frames
<decorator-gen-63> in load_ext(self, module_str)

/usr/local/lib/python3.6/dist-packages/tensorboard/notebook.py in load_ipython_extension(ipython)
     98     """
     99     raise RuntimeError(
--> 100         "Use '%load_ext tensorboard' instead of '%load_ext tensorboard.notebook'."
    101     )
    102 

RuntimeError: Use '%load_ext tensorboard' instead of '%load_ext tensorboard.notebook'.
```

**Comment by ys7yoo** [comment]
fixed code, but another error
```
ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
2020-11-20 13:57:44.910122: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
/usr/local/lib/python3.6/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 65, in run_main
    default.get_plugins(),
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/default.py", line 113, in get_plugins
    return get_static_plugins() + get_dynamic_plugins()
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/default.py", line 151, in get_dynamic_plugins
    "tensorboard_plugins"
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/default.py", line 150, in <listcomp>
    for entry_point in pkg_resources.iter_entry_points(
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.26.2 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})
```

**Comment by ys7yoo** [comment]
tried the following
```
!pip uninstall -q tensorboard tb-nightly
!pip install -q tensorboard  
```
from 
https://github.com/tensorflow/tensorboard/issues/2748#issuecomment-539791539

Still not working
